version: '3.8'

services:
  task:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    environment:
      DISABLE_DEFAULT_SERVER: 1
      PHP_IDE_CONFIG: "serverName=taskApp"
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=host.docker.internal remote_port=9081
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./vendor:/var/www/vendor/
    ports:
      - 9081:9081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    stdin_open: true


